### PR TITLE
Add data persistence to collaboration sessions, chat updates, event bus for matching-collaboration and ensure validity of room/users

### PR DESCRIPTION
**Pull request by weidak**
# Pull Request

## Description

This PR provides caching functionality and allows users to restore code, session time and chat history. Currently, every session is set to end within 1 hour. 

================ UPDATE on 21/10 ===================

Add event bus between matching and collaboration service to ensure validity of rooms and users.

image

### Setting up for development

Install docker engine:

```
$ sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Or for windows download <a href="https://docs.docker.com/desktop/install/windows-install/">here</a>

Run this command to cache session database details:
```
$ sudo docker run -p 6379:6379 --name peerprep-database -d redis
```

Run event bus between matching and collaboration service:
```
$ sudo docker run -p 6380:6379 --name peerprep-eventbus -d redis
```

_/backend/collaboration-service/.env_ 
```
SERVICE_PORT=5300
REDIS_URL=redis://localhost:6379/
REDIS_EVENT_BUS=redis://localhost:6380/
LOG_LEVEL=info
```

_/backend/matching-service/.env_ 
```
NODE_ENV=development
SERVICE_PORT="5200"
MATCHING_TIMEOUT=10000
LOG_LEVEL="debug"
REDIS_EVENT_BUS=redis://localhost:6380/
```

Removing the containers (if needed):
```
$ sudo docker stop peerprep-database
$ sudo docker stop peerprep-eventbus

$ sudo docker remove peerprep-database
$ sudo docker remove peerprep-eventbus
```

==================================================

## Related Issue(s)

#86 Managing sessions on collaboration-service
#82 Implement tests/error handling on collaboration-service

================ UPDATE on 21/10 ===================

#107 Implementing communication (event stream) between matching and collaboration service

==================================================

## Changes Made

- Added caching to allow managements of sessions active within the socket server
- Handle ending of session when timer hits 0 in client side
- Changed it such that timer shows on entering of the workspace/code editor
- Added tests for the socket handlers
- Added mock database implementation for test environment
- Updated github workflow to accommodate new CI 
- Updated logger packages for matching and collaboration service 
- Added chat toggle to move left or right
- Added notification bubbles to chat

================ UPDATE on 21/10 ===================

- Removed the ability to send chat messages when partner is not connected
- Added validity checks for roomId and userIds, such that a user that do not belong in that room is unable to join (Both redirect to 404 not found)
- Users can still continue the session even when their partner disconnected with a new toast that indicates the termination of their session.
- Users that have terminated their session are no longer able to join back into the server because the backend invalidates their userid for that room.
- Added new listeners on both front and backend to accommodate changes thus allowing us to handle more complex situations above.

==================================================

When the session starts:
1. Caches when session is supposed to end (current time + 1hr)
        _- Checks if room exist, else 404
        - Checks if user is valid, else 404
        - Load cached content (if exists)
        - Load chat messages (if exists)_
3. On code change, it will cache the content of the editor
4. On new chat messages, it will cache the chat content
5. On manual session termination, it will prompt the user
        _- Emits an event to initiate end session
        - Prompts backend to remove validity of userId_
7. On session end on timer, a modal will prompt the user to leave the room. 

## Screenshots (if applicable)

Shows partner disconnection:
image

Session ended (due to timeout). This will keep reappearing even if user exits the modal (as it checks that time is negative)
image

Chat notification bubble:
image

================ UPDATE on 21/10 ===================

Disable sending of chat when partner not connected:
image

Partner terminates session:
image

Ensuring room validity:
image

==================================================

## Checklist
- [x] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [x] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [x] I will take care of the merging and delete the side-branch after the PR is merged.

## Additional Notes/References
Things to do:

- Post item to history service when history service ready
- Dockerize service #101

### CODE REVIEW

**Comment by tryyang2001** [comment]
Ermm, I will suggest that we don't share the .env secret in GitHub for good and safe practice...

**Comment by tlyi** [comment]
> * Fix on leaving function 

I think that this can be solved by making sure that the backend socket service is aware of both user ids? This way, the room would not allow a new socket to join if the user requesting to join is already inside the room. This ensures there are only 2 sockets connected to each room belonging to 2 different users.

Also, since now the user (A) is aware of the connection status of the other user (B), wouldn't it be sufficient to check if the B is still connected when A leaves to determine if this is the last user left in the room? Or am I missing something here? 😖

**Comment by weidak** [comment]
> I think that this can be solved by making sure that the backend socket service is aware of both user ids? This way, the room would not allow a new socket to join if the user requesting to join is already inside the room. This ensures there are only 2 sockets connected to each room belonging to 2 different users.

Oh this is a great idea! I haven't gotten to that part yet oops but i'll write this down and implement it. Thanks! 👍🏻 

> Also, since now the user (A) is aware of the connection status of the other user (B), wouldn't it be sufficient to check if B is still connected when A leaves to determine if this is the last user left in the room (and vice-versa)? Or am I missing something here? 😖

I think it is possible to do this, lemme try. Also, I am trying to understand what is causing the extra connection(s) being initiated from the frontend to the backend. Currently, It has 3 active sockets in a room that contains 2 users and these are its behaviours:

1) Upon room creation, 3 sockets are connected:

image

2) Upon both user refreshing pages together, 3 sockets are also connected:

image

3) Refreshing one user:

image

4) Refreshing the OTHER user:

image

The behaviour is such that refreshing either users will reduce the active connections  from 3 to 1. I am not sure why this is the case and I am honestly just confused at this point. I will try to change the way my `socket_service.ts` instantiate to Junsheng's `socket_service.ts`  to see if it makes any difference.

**Comment by weidak** [comment]
Update: the pr is ready now alongside with jest implemented

**Comment by c0j0s** [comment]
Some issues:

1. typo
image

2. small clipping at the floating chat button
image

3. partner connection status
    might be good to toast the user if the partner gets disconnected. cos the icon is too unnoticeable, user might feel ghosted if he did not notice the status change....

3. Another thing is that if the partner chooses to terminate the session, can the user continue the session? if so, the end session prompts that "action is irreversible" but since the session is still live, the partner can still press backward and get back to the session.... so is it intended to be "irreversible"?

5. Is it possible to move the chat button to the left-hand corner? cos from user experience point of view, allowing users to view chat messages while coding might be more effective for a collab session since we don't have other forms of communication mode yet. blocking the question shouldn't annoy much I guess.

6. Since the NavBar allows navigating to home or user profile, the user can exit the session without hitting the end session button, will it have any side effect on the session? feels weird to allow them to freely navigate out of the collab session also. 
image

7. We might need a way to determine the validity of the roomId. the user can start a new collab session without going through the matching service using a terminated session roomId and arguments....

**Comment by tryyang2001** [comment]
I guess I can help discuss some of the questions:
> so is it intended to be "irreversible"?

The end session button is created by me, and my initial thought is that once the user terminates the session, he or she should not be able to go back to the room anymore. Not sure if you guys wanted to implement this? If not can just update the modal message.

> Is it possible to move the chat button to the left-hand corner? blocking the question shouldn't annoy much I guess.

Yes it is entirely possible. But one issue is that the chat button might block the question details since its position is set to `absolute`. Another idea that I can think of to "not block the code editor" is that we can make the chat space draggable so that the user can drag it to somewhere else if it is blocking the editor??

> might need a way to determine the validity of the roomId
The most simple idea I  can think of is to put the room id in the database, and we check if the room id exists in the db before letting the user go into the collaboration workspace, what do you think?

**Comment by weidak** [comment]
@c0j0s thanks for the super detailed reivew :D 

1. fixed!

2. my screen was so small i didnt notice.. fixed too

3. ah thats quite true.. thanks for the suggestion! i have added partner connected/disconnected toasts:
image
image

4. for this, a possible implementation to make it irreversible is that your matching service/components are the only ones that can set a flag to true, and our collab can only set the flag to false when timer runs out or a user manually leaves the session. what do u think? @tryyang2001 pls advise too

5. ok to satisfy everyone i have made a toggle to move chat to left or right:

image
image

6. i agree with ur point, and it introduces more undesired actions by users while collab-ing

7. we can also encode the datetime of when they were matched inside roomId, such that we can decode the roomId to determine the room validity and making each room id truly unique. what are your thoughts?

**Comment by tryyang2001** [comment]
> for instance matching-service sets isMatched = true, and collab-service sets isMatched = false upon termination

I doubt this will work for all cases. The problem is that we have no way to determine what should be the `isMatched` state. Here is a counterexample: 
I believe we will first initialise this `isMatched` flag to `false` to prevent unauthorized entry into the room. When two people get matched and entered the room, and one of them closed the browser (for whatever reason) and have to restart the app. Then, when he returned, will this `isMatched` flag still be set to `true`? As we have no way to determine what should be its current value, I guess the app will simply follow the initial value and the user cannot go back? (please correct me if my understanding is wrong). My recommendation is to simply create a database to store the valid room ID if we really want to tackle this issue.

**Comment by tryyang2001** [comment]
> feels weird to allow them to freely navigate out of the collab session also.

If you guys want to fix this, one idea that I have is that we put a modal to confirm if the user really wants to navigate (similar to when u attempt Canvas/Luminus Quiz). I believe the only side effect is that the user will not be in the room to collaborate, but the timer will still be counting.

**Comment by weidak** [comment]
Updated! (ready to merge, pls look at those with)
================ UPDATE on 21/10 ===================

**Comment by tryyang2001** [comment]
One feedback from my side is that if the user accidentally exit the current page, as long as it is not pressing the "end session" button, shall we let him to join back the room again? Or at least we prompt a modal to confirm exit before we kick him out?

**Comment by weidak** [comment]
@tryyang2001 ahh thanks! I realised the service was not behaving as it should. I have updated it such that :

- If a user refreshes or leaves the session by clicking away on the navbar/back button, he will be able to join back through the same link. 
- This means that the backend keeps track of the sessions and will terminate them after 1hr 10seconds (which is the key expiry for redis) 
- Only when a user leaves the room through the "End session" button then they are unable to return to the same room, making the terminate session action irreversible.

hope that clarifies

**Review by tryyang2001 — APPROVED** [review]
Approve this PR to get merged to master as the proposed features are working correctly. Thanks @weidak for integrating and improving the collaboration service!

**Pull request merged**
