### PR TITLE
Format Input Error Message Returned in Backend Servers (User & Question)

### LINKED ISSUE #39: [Question Service] Message value format in PUT response
image

is stringified json the intended return format?
@tryyang2001 @xingjie99 

thanks

### PR DESCRIPTION
**Pull request by tryyang2001**
# Pull Request

## Description

Before this PR, the error message due to the invalid request body given is hard to read, see example reported by @c0j0s :
image
The goal of this PR is to convert this error message to a meaningful string. For details, see the screenshots.

## Related Issue(s)

Fixes #39 

## Changes Made

- update the returned error message format
- update unit tests for the latest changes
- remove the integration test for now as it is buggy.

## Screenshots (if applicable)

When a given input is too short/long, the error message will be:
image

When a required field is not provided, the error message will be:
image

A special case for `examples` in question service, if the necessary `input` or `output` is not given, the error message will be:
image

When a array field is given with an empty array, the error message will be:
image

There are other cases. Take note that with this new returned format, the error message will always be a one-line string. 

## Checklist
- [x] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [x] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [x] I will take care of the merging and delete the side-branch after the PR is merged.

### CODE REVIEW

**Review by c0j0s — APPROVED** [review]
As I mentioned, returning a single error message is not that intuitive for the error feedback in forms. 
I'll approve this PR first and continue this discussion in #39.

**Comment by tryyang2001** [comment]
Oh my bad, I was assuming on the frontend side there will be some parsers to check input validity. However, if you don't have any plan to implement such parser/useEffect, I will update my API response to include multiple different error messages. Maybe in the later PR?

**Comment by c0j0s** [comment]
I can include a parser to validate the form. but what if we decide to change certain validation rules later on, we'll need to ensure both frontend and backend logic are in sync. pushing the validation entirely in the backend helps to simplify this bah, the form can simply reflect the state of the submission.
There are pros and cons for both approaches I guess, what are your thoughts?

**Comment by tryyang2001** [comment]
I think no matter frontend has a parser or not, we always need to check the request body in backend. Because we can't assume all requests are coming from our app only, at least for now.
Checking on the frontend side gives benefit to speed I guess, as there is no need for API calls. However, it is true that frontend and backend validators can be different in the future. So I am fine with either you have or don't have a parser in the frontend. 
With that, I confirm with you that I will give multiple error message for this case. It is quite doable. 
But I will create another PR for that, let's merge this for now I guess.

**Comment by tryyang2001** [comment]
Hi @c0j0s , I am sorry, but returning multiple error messages can be quite complicated. 
I have an invalid request body:
image

And the returned error message can be like this:
image
To read this error message, those that displayed as an array correspond to the array elements that caused the error.

And this is not the only issue. Since I am checking your input "topics" must belong to one of the enums we defined. When there is an enum not equal, I will throw an error. But this error will overwrite the Zod Schema issues. So you will only get one error message which indicates that your topics provided is invalid. 

And the code is quite complicated, sorry bad programmer here :((

To resolve the above mentioned issue, I can only think of a few options:
1. Don't return multiple error messages, use a frontend parser instead (I am more prone to this, I can help create parser if you need)
2. Don't check each topic provided is in one of the enum we defined, this will make database to potentially store invalid topics
3. Find a way such that it allows us to throw `ZodError` but not blocking the other error to be identified. (I can't find any way of doing this after 2 hrs of works, need help...)

**Comment by c0j0s** [comment]
No worries, let's deal with a single error message for now first bah, it's not the priority. maybe you can merge this PR and commit your changes to a separate branch first. 
I'm not familiar with zod so let me take a look first and see what can be done bah. 
Worst case sticking to the current changes is fine for me 🙂

**Comment by tryyang2001** [comment]
Thank you! I think we can discuss in the future... Or maybe after a few days I suddenly have an idea how to do that :P.
So I will merge this PR now!

**Pull request merged**
