### PR TITLE
Create History Service Frontend

### LINKED ISSUE #84: Create history service (frontend)
- Heatmap, statistics

### PR DESCRIPTION
**Pull request by tryyang2001**
# Pull Request

## Description

Created questions statistics such as number of questions solved by topics, complexities, and languages. Also shown the attempted questions in a table list. To enhance Ui, I also created a heatmap for past 6 months submissions. 

## Related Issue(s)

Closes #84 

## Changes Made

- update history_api_wrappers
- create more donut charts
- create heatmap
- create question statistics table
- set React `strictMode` to false to prevent the heatmap gets drawn twice
- move `providers.tsx` under `/context` path so that it is easier to find it
- added icon for tabs

## Screenshots (if applicable)

The overall dashboard layout will be like this (updated):
image

Taking a closer look at the heatmap:
image
- it supports rendering tooltips on cell hovering!
- there is a legend showing the color range of the heatmap cells, but it cannot show any tooltip on hover
- there is a link in the bottom that will navigate you to the `/questions/history` page

The question history page will show all the attempted questions in a table, the table is sortable for question title, complexity, and submission date:
image

We can show more topics solved in case it overflows, of course we can also hide it back:
image

## Checklist
- [x] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [x] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [x] I will take care of the merging and delete the side-branch after the PR is merged.

## Additional Notes/References

- Thankfully I found a pretty nice calendar heatmap that supports showing tooltips! This library is called [cal-heatmap](https://www.npmjs.com/package/cal-heatmap), feel free to explore more in your free time.
- I have to disable the React `strictMode` to prevent the heatmap renders twice. This will not happen in the production environment, so feel free to re-enable the strict mode when you think you need to do some proper testing.
- I will continue working on this PR to add a modal page for showing attempted question code submission, and make the question table rows clickable
- I want to report a bug that I noticed in the matching card. When I navigate to the dashboard page by clicking the "Home Button" in the top left corner of the nav bar, my preference will disappear, but refreshing the page will get it work again, not sure what happen, do you mind helping me to take a look, @c0j0s ? To reproduce the error, follow these steps:
1. Navigate to a not `dashboard` page, eg: `/questions`
2. Go back `dashboard` page by clicking the home button in the nav bar
3. The preference will disappear, or at least in this branch. Let me know if it only occurs in this branch.

### CODE REVIEW

**Comment by tlyi** [comment]
Woah looks great!! Thanks @tryyang2001 ! 😄
Some suggestions for additional features on the question statistics table:
-  Search for question/topic
-  Sort for complexity
-  Add a "View all" that will allow the user to see all the attempted questions in a page
-  Add an additional column to show the topic corresponding to the attempted question 

These are just suggestions, feel free to implement or not :D

**Comment by tryyang2001** [comment]
Thanks for the suggestions!
 
> Search for question/topic

For this, I think we can postpone until we want to enhance our questions table to support search and filters. Then we can improve both the history table and the question table together.

> Sort for complexity

Sure, I will think of a way to implement it.

> Add a "View all" that will allow the user to see all the attempted questions in a page

Good idea, I will try to implement this.

> Add an additional column to show the topic corresponding to the attempted question

In my original table, I did include this column. However, unlike the questions page which we have the whole page to render the table, showing the topics will make the history table become very compact and thus I think it is better to not include it. :P

**Comment by tryyang2001** [comment]
For this PR, I am not going to do the integration for history. I will make another PR for the integration. So this PR will only deal with the frontend components :)

**Review by weidak — APPROVED** [review]
LGTM

**Comment by tryyang2001** [comment]
I will merge this PR by tonight if there is no further suggestion :). Thanks!

**Pull request merged**
