### PR TITLE
Fix Question Detail Page not working

### PR DESCRIPTION
**Pull request by tryyang2001**
# Pull Request

## Description

I think there are issues in the individual question detail page, which causes the page failed to load. I don't know what is the intended fix and so I simply convert this page to a client component. Now this is working. Please help review and give ideas, thank you! 

## Changes Made

- convert `questions/[id]/page.tsx` to a client component

## Checklist
- [x] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [x] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [x] I will take care of the merging and delete the side-branch after the PR is merged.

## Additional Notes/References

@c0j0s please let me know if you are already working on this issue, and I will close this PR. If not, I think we can merge this first so that we can update our assignment tagging.

### CODE REVIEW

**Comment by c0j0s** [comment]
I ran the master branch and the question details page works on my side hmm....

**Comment by tryyang2001** [comment]
Oh my bad, I think it only fails in my new branch, I will fix the issue on that branch... Sorry!

**Comment by c0j0s** [comment]
I read your collab PR, seems like you removed "use client" in the problem description component, I think this might be the reason.

**Comment by tryyang2001** [comment]
Yes indeed that is the reason haha. Thanks for letting me know. I will push this fix to my PR.

**Pull request closed without merging**
