### PR TITLE
Code Execution

### LINKED ISSUE #108: Implement code execution functionality

### PR DESCRIPTION
**Pull request by tlyi**
# Pull Request

## Description

- Code compilation 
- Test case execution with automated input parsing for Python and Javascript, so that users do not need to read in inputs manually
- Frontend components to support this feature

**UPDATE**:
- I have decided to remove support for automatic test case execution in both C++ and Java, as it was parsing some inputs wrongly, which might actually break the users' code instead... So now there's only code compilation + output feature for these 2 languages :"D 
telegram-cloud-photo-size-5-6226263915935939931-y

Putting out this PR so that you guys can try to break the functionality asap :D 

**NOTE:** Remember to add in`NEXT_PUBLIC_RAPID_API_KEY`, `NEXT_PUBLIC_RAPID_API_KEY`, `NEXT_PUBLIC_RAPID_API_URL` in the frontend env :) 

**To be done in the same PR before closing:** 
- [x] Make the instructions in the "add question" modal clearer so that admin does not end up adding an example that will break the code exec 

## Related Issue(s)

Closes #108 #130 

## Screenshots (if applicable)

Correct code attempt: 
image

Manual testcases/C++/Java (checking of correctness not supported for these):
image

Compilation and runtime errors are shown. E.g: Error from inputting a wrong input format:
image

**Updated code templates**:
telegram-cloud-photo-size-5-6226263915935939866-y
telegram-cloud-photo-size-5-6226263915935939912-y
telegram-cloud-photo-size-5-6226263915935939986-y
telegram-cloud-photo-size-5-6226263915935940018-y

Clarify input guidelines:
image

## Checklist
- [x] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [x] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [x] I will take care of the merging and delete the side-branch after the PR is merged.

### CODE REVIEW

**Comment by c0j0s** [comment]
1. misleading comment for java
   I thought I had to call the main method to run the code like python.
   image
2. maybe a more helpful hint for cpp, for non-cpp user like me 🙃
   image
   also, the hint is misleading as well, unless I'm wrong with how cpp works.
   image

**Comment by weidak** [comment]
Yah, I agree with junsheng's pov on this.. There seems to be a learning curve on this, realised how rusty i was at the same time... Otherwise, its working n good enough for demo 👍🏻

**Comment by weidak** [comment]
Suggestion to add this import for cpp so users dont need to #include <vector> and other libraries

image

**Comment by tlyi** [comment]
> Suggestion to add this import as default code for cpp so users dont need to #include and other libraries
> 
> image

Ooh good idea! Thanks!!

**Comment by tlyi** [comment]
@c0j0s thanks for the feedback! have updated the template codes to hopefully be clearer 😅

**Comment by weidak** [comment]
image

Misaligned panels due to new (i) button, fixed it as well as frontend build check in my commit

**Comment by weidak** [comment]
@tlyi has removed code execution for cpp and java, making them compile-only with full execution support for python and javascript. will justify this in the report with something like this article: https://bootcamp.berkeley.edu/blog/most-in-demand-programming-languages/

**Review by weidak — APPROVED** [review]
LGTM, will still have to bug hunt but at least we can try to deploy this first

**Pull request merged**
