### PR TITLE
Patch Question Service

### PR DESCRIPTION
**Pull request by tryyang2001**
# Pull Request

## Description

There are some mistakes made in the question service API. 
- the MongoDB dependency is not put in the `package.json`.
- the response data of `getQuestionById` does not align with what we are expecting. 
- the enum checking is inconsistent with user service as it is still case-sensitive.
This PR should fix all the issues mentioned above.

## Related Issue(s)

Fixes some issues mentioned in #32 

## Changes Made

- update `package.json` to include `mongodb` dependency
- update `getQuestionById` response data format
- update `convert` methods in `Topic` and `Complexity` enum to make it case-insensitive
- update `questions.json` (which includes 20 questions from the pdf in json format, though some details may not be there yet)
- use `mongoose` to interact with the database
- define question schema

## Screenshots (if applicable)

From local test result, the `getQuestionById` endpoint should now return the question object directly, see screenshot below:
image

An example of the question data in `questions.json`, note that when you use it, remove the `id` field in the request body.
image

## Checklist
- [x] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [x] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [x] I will take care of the merging and delete the side-branch after the PR is merged.

## Additional Notes/References

I am actually more incline to use [mongoose](https://mongoosejs.com/docs/guide.html), which is like "Prisma" but for "MongoDB" only as it is more clean and we can define schema also.

### CODE REVIEW

**Comment by c0j0s** [comment]
didn't see the changes for getQuestionById, get-handler.ts should be included?

as for database as long as its nosql should be fine for assignment ba, but since we are moving questions to SQL DB later on then mongo should be enough.

unless you plan to keep question in nosql.

**Review by c0j0s — APPROVED** [review]
LGTM

**Comment by tryyang2001** [comment]
Ops @xingjie99 , I accidentally push the mongoose update to this PR... can you help to take a look and if you are okay with the changes, I will merge this PR. If not, I will revert the commit and merge the PR without the mongoose update.

**Comment by xingjie99** [comment]
> as for database as long as its nosql should be fine for assignment ba, but since we are moving questions to SQL DB later on then mongo should be enough.
> 
> unless you plan to keep question in nosql.

Same thought here which was why I did not include mongoose since mongoDB has already provided functions that are relatively easy to use to insert.



> Ops @xingjie99 , I accidentally push the mongoose update to this PR... can you help to take a look and if you are okay with the changes, I will merge this PR. If not, I will revert the commit and merge the PR without the mongoose update.

 However I dont see much of an issue if you changed it to mongoose and everything is working. I think we can just keep it. LGTM, will test it after merging thank ruiyang!

**Pull request merged**
