### PR TITLE
Implement image uploading service for users (Profile management)

### PR DESCRIPTION
**Pull request by weidak**
# Pull Request

## Description
Previously, CRUD operations did not involve profile picture insertions due to the use of S3 client/UploadThing client
This PR is to implement it fully with working functionality, able to extract url from the image database and save it into User in the PostgreSQL database.

## Related Issue(s)

#75 

## Changes Made

EDIT: Rui Yang moved the S3 client to be on the frontend, thus no need to deal with it in the backend anymore. Thanks @tryyang2001 !! :D so happy this is finally done

The S3 client is now hosted on the frontend, makes a POST api call to send the file to the S3 client before uploading it to a S3 bucket.

## Screenshots (if applicable)

Uploading a new picture (Click save to confirm changes)
image

Done (navbar changed too)
image

## Checklist
- [x] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [x] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [x] I will take care of the merging and delete the side-branch after the PR is merged.

## Additional Notes/References
Done ✔️

### CODE REVIEW

**Comment by c0j0s** [comment]
> No matter what I tried, I couldnt get the process.env.{variables} to load in even though one is server side and the other is in client component, and the console log shows some weird messages.

if I'm not wrong "use server" does not allow exporting of const objects, the only way is to put it behind an async server action for your FE to consume.

**Comment by weidak** [comment]
> > No matter what I tried, I couldnt get the process.env.{variables} to load in even though one is server side and the other is in client component, and the console log shows some weird messages.
> 
> 
> 
> if I'm not wrong "use server" does not allow exporting of const objects, the only way is to put it behind an async server action for your FE to consume.

Ahhh yeah I found that out while implementing the websocket/collaboration service LMAO.. 

Anyways thanks rui yang for figuring it out!! really happy 😭

**Review by c0j0s — APPROVED** [review]
in that case, I'll approve it first.

**Comment by weidak** [comment]
@tlyi @xingjie99 Will merging this branch cause implications to the authentication implementation? If it does, I'll merge it sometime next week since it's not urgent 👍🏻

**Comment by tlyi** [comment]
> @tlyi @xingjie99 Will merging this branch cause implications to the authentication implementation? If it does, I'll merge it sometime next week since it's not urgent 👍🏻

LGTM! There'll be some merge conflicts but you can merge this first and i'll resolve it in the auth branch :)

**Comment by tryyang2001** [comment]
Our current implementation is that the front end will directly communicate with the AWS S3 Bucket service. That's why you see that we created a POST API in our frontend `api` path. We can move this image upload operation to user service for better separation of concern. Still, since the front end and user service are hosted in different domains (different ports for localhost), the file transfer tends to be slower than local operation. Therefore, we chose to upload the image directly from the front end. The consequence is that this will minorly break the concept of microservices, but I think this should be fine. If you all agree for the current implementation then we can merge this PR! Then we will be able to change the user profile picture hehe. 😄

**Pull request merged**
